"""生成 dlssg_for_sm86 的 dlssg_sm86.ini（键与上游一致，注释中英双语）。"""

MFG_PRESET = {"2x": 1, "3x": 2, "4x": 3, "6x": 5}

_TEMPLATE = """\
; dlssg_sm86.ini — 由 dlss-combo 生成 / generated by dlss-combo
; 画质层: DLSS5-Swapper (DLSS 5 神经渲染)  插帧层: dlssg_for_sm86 (DLSS-G)
; 改动后需重启游戏 / restart the game after changes.
; 完整诊断键位见上游 docs/INSTALL.md / see upstream docs/INSTALL.md for every key.

[General]
; 1 = 帧生成开（内嵌 Ampere 优化的 DLSS-G 运行库）/ 1 = frame generation on
Enabled=1

[FrameGeneration]
; 一致性档位：0 原厂内核最保守；1 全部逐位一致加速（推荐默认）；
; 2 在 1 上加 ~50dB PSNR 有损内核（仅 310.9）；3 全部有损最快。/ consistency tier 0-3.
Optimized={tier}
; 插帧上限：3 = 最高 4X（默认）；5 = 最高 6X（仅 310.9 且游戏自身支持）。
; / ceiling: 3 = up to 4X (default), 5 = up to 6X (310.9 build + game support).
MaxGeneratedFrames={max_generated_frames}

[Compatibility]
; UI 重合成档位（仅 310.9）。Auto = 交给游戏/驱动。/ UI recomposition preset, 310.9 only.
Preset=Auto

[Logging]
; 0 关 / 1 仅错误 / 2 配置与能力 / 3 内核追踪。/ 0 off, 1 errors, 2 config, 3 traces.
Level={logging_level}
Directory=dlssg_sm86\\logs

[Runtime]
; Bundled = 始终用内嵌配套运行库（常规用法）/ always use the embedded matched runtime.
Mode=Bundled
CacheDirectory=
"""


def build_ini(tier: int = 1, mfg: str = "4x", logging_level: int = 1) -> str:
    """按预设生成 INI 文本；非法 tier/mfg/logging_level 抛 ValueError。"""
    if not isinstance(tier, int) or not 0 <= tier <= 3:
        raise ValueError(f"tier must be 0..3, got {tier!r}")
    if mfg not in MFG_PRESET:
        raise ValueError(f"mfg must be one of {sorted(MFG_PRESET)}, got {mfg!r}")
    if not isinstance(logging_level, int) or not 0 <= logging_level <= 3:
        raise ValueError(f"logging_level must be 0..3, got {logging_level!r}")
    return _TEMPLATE.format(
        tier=tier,
        max_generated_frames=MFG_PRESET[mfg],
        logging_level=logging_level,
    )
